export const SET_EXPERIENCES_TYPES = {
  SET_EXPERIENCE: 'SET_EXPERIENCE',
  SET_POSITION: 'SET_POSITION',
  SET_EMPLOYER: 'SET_EMPLOYER',
  SET_START_DATE: 'SET_START_DATE',
  SET_END_DATE: 'SET_END_DATE_KN',
  SET_EXP_DESCRIPTION: 'SET_EXP_DESCRIPTION',
  SET_DELETE_EXPERIENCE: 'SET_DELETE_EXPERIENCE'
}