export const PERSONAL_INFO = {
  SET_NAME: 'SET_NAME',
  SET_LASTNAME: 'SET_LASTNAME',
  SET_IMAGE: 'SET_IMAGE',
  SET_EMAIL: 'SET_EMAIL',
  SET_NUMBER: 'SET_NUMBER',
  SET_ABOUT_INFO: 'SET_ABOUT_INFO'
}